### ISSUE TITLE
ARM 1.4.1

### ISSUE THREAD

**Issue by jimoverly** [SoftFever/BambuStudio-SoftFever#100]
The Arm version of 1.4.1 shows to be corrupt.  1.4.0 opens fine
![Screenshot 2023-01-02 at 1 18 32 PM](https://user-images.githubusercontent.com/16322332/210267029-78cfc671-2fa1-4ee8-9912-a4a604f6f130.png)

**Comment by hliebscher** [comment]
Please check NOTE 1 part in the release notes: https://github.com/SoftFever/BambuStudio-SoftFever/releases/tag/v1.4.0

**Comment by jimoverly** [comment]
Interestingly the 1.4.0 version didn't have this issue.

**Comment by hliebscher** [comment]
pls use at Terminal 

xattr -d com.apple.quarantine  /Applications/BambuStudio-SoftFever.app

**Comment by SoftFever** [comment]
It looks like the problem has been solved.
I'm closing it
