### ISSUE TITLE
Object Flow Ratio Does Not Support Decimals

### ISSUE THREAD

**Issue by CaZa3D** [SoftFever/BambuStudio-SoftFever#103]
**Describe the bug**
When changing flow ratio under specific objects to decimals  such as 95.5%, they revert back to hole numbers such as 95%

**To Reproduce**
1. Click Objects
2. select object
3. Quality tab
4. Set flow ratio to 95.5%
5. click away
6. click back on object
7. flow ratio is now at 95%

**Expected behavior**
I expect to type 95.5% and it to stay at 95.5%

**Screenshots**
![95](https://user-images.githubusercontent.com/121848948/210308916-e5a91cdf-0ce3-46c1-92f9-35f93ff2a075.png)
![955](https://user-images.githubusercontent.com/121848948/210308919-762c6e87-1fdf-41da-af26-de6972ed5e34.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 x64
 - Version Softfever  1.4.1

**Comment by hliebscher** [comment]
at osx 13.1 is the same
does it make sense? the deviation from the filament is greater

**Comment by SoftFever** [comment]
It's a UI bug. It will be fixed in the next update.

**Comment by SoftFever** [comment]
> 

I guess it depends on the base flow ratio set in the filament setting.
If that is set to 1, then 1% is too big

**Comment by SoftFever** [comment]
Fixed.
Will be supported in next release
