### ISSUE TITLE
GCode error Fan number 2 not found  during print

### ISSUE THREAD

**Issue by hliebscher** [SoftFever/BambuStudio-SoftFever#105]
**Error: Fan number 2 not found**

M572 D0 S0.05; Override pressure advance value
M106 S0 ; disable fan
**M106 P2 S0 ; disable additional fan**  <<-- it is only for BBS Printer 

i think its in the file print.hpp
 
   //SoftFever
    bool &is_BBL_printer() { return m_isBBLPrinter; }
    const bool is_BBL_printer() const { return m_isBBLPrinter; }
    CalibMode& calib_mode() { return m_calib_mode; }
    const CalibMode calib_mode() const { return m_calib_mode; }

**Comment by SoftFever** [comment]
I keep that option available to all printers on purpose. 
Nowadays, the auxiliary fan is not rare among DIY printers.
Users can define a macro to enable this command.
(not sure if RRF can override a builtin command, Klipper can)

**Comment by SoftFever** [comment]
Anyway, unticking this option in the printer settings should solve your problem in case you don't have an auxiliary fan.
![image](https://user-images.githubusercontent.com/103989404/210390109-d32f2cd2-f5de-4ffd-974f-1fdd0d0507b8.png)

**Comment by hliebscher** [comment]
it is in all gcodes 
the aux is not enabled 

; filament start gcode
M572 D0 S0.025; Override pressure advance value
M106 S0 ; disable fan
M106 P2 S0 ; disable additional fan 
;LAYER_CHANGE

**Comment by hliebscher** [comment]
![Ohne Titel 2](https://user-images.githubusercontent.com/9274162/210391252-6c0c2ed2-f2ca-4104-9d27-8b45d1a0fe7f.jpg)

**Comment by SoftFever** [comment]
Noted.
It's bug then

**Comment by SoftFever** [comment]
Fixed.
