### ISSUE TITLE
don't select TRONXY printer it crashes the app on MAC !!!

### ISSUE THREAD

**Issue by hliebscher** [SoftFever/BambuStudio-SoftFever#108]
after selecting Tronxy it crashes 
is not possible to restart it crashes again

only kill the config directory helps...

Failed loading configuration file /Users/hliebscher/Library/Application Support/BambuStudio-SoftFever/system/Tronxy/machine/Tronxy X5SA 400 0.4 nozzle.json
Suggest cleaning the directory /Users/hliebscher/Library/Application Support/BambuStudio-SoftFever/system firstly

it is reproducible 2 times

**Comment by SoftFever** [comment]
https://github.com/SoftFever/BambuStudio-SoftFever/pull/81#issuecomment-1370355732

**Comment by erebus04** [comment]
I'm looking at this on my Mac. Which MacOS version are you using?

**Comment by SoftFever** [comment]
@erebus04 I believe this happens on all OS.
You can reproduce it by remove `~/Library/Application Support/BambuStudio-SoftFever/system` folder then run the application again.

**Comment by erebus04** [comment]
Ok thanks. I Check all
