### ISSUE TITLE
Show the current filament in use, no matter which AMS is selected.  i.e. Switch focus to current AMS

### ISSUE THREAD

**Issue by SwagDad99** [SoftFever/BambuStudio-SoftFever#11]
Issue:
Right now, when using more than one AMS, if the filament in use is from a different AMS than the one that has 'Focus', or is selected above the filament colors, it shows a 'blank' color in the extruder, and no color in the 'Path' from spool to extruder.  It should show the current path from the spool in use to the extruder.

Resolution:
In the device tab, while using more than one AMS, when the filament begins coming from the alternate AMS, switch focus to that AMS so that the extruder and path show the correct color, rather than keep it blank unless it is manually selected by the user.

**Comment by SoftFever** [comment]
The proposal makes perfect sense to me.
Unfortunately, I don't have the time to investigate this issue. 
Hopefully, BL can solve it soon.

**Comment by SwagDad99** [comment]
Are they, Bambu, aware of the issue?  Do they see what is posted to your GitHub, or does it need cross posted to theirs?

Thank you,

Don
