### ISSUE TITLE
First Layer printing indicator

### ISSUE THREAD

**Issue by cdmichaelb** [SoftFever/BambuStudio-SoftFever#110]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
While the first layer is printing, have some kind of indicator.

**Describe alternatives you've considered**
AI Failure detection, however it does not prevent failures.

**Additional context**
I would like to print my prints at manual 50% speed for first layer, even with the defaults set to lower speeds I still have some failures. However I have no way of knowing if it's currently printing first layer, or additional layers.

Thanks.

**Comment by cdmichaelb** [comment]
I ended up just lowering the default, but I still think it would be nice to know if first layer has succeeded.

**Comment by SoftFever** [comment]
I also would like to see this feature.
Unfortunately, there is not much we can do here(forked slicer) ourselves. 
It is entirely up to Bambu to add features in their firmware."
