### ISSUE TITLE
Vase mode does not work 

### ISSUE THREAD

**Issue by rollduck** [SoftFever/BambuStudio-SoftFever#117]
**Describe the bug**
Afert vase mode selection an error occurs:
"Unhandled unknown exception; terminating the application"
06:44:36: BambuStudio got an unhandled exception: boost::bad_any_cast: failed conversion using boost::any_cast
06:44:36: BambuStudio got an unhandled exception: boost::bad_any_cast: failed conversion using boost::any_cast

**3mf File for This Bug**
No matter what object we would like to slice. 

**To Reproduce**
1. Just select and confirm spiral vase

**Expected behavior**
I expected a sliced model :) 

**Screenshots**
![spiral_vase](https://user-images.githubusercontent.com/54622876/210711927-ab0810fa-b343-4cdd-ba7d-4c5889d9f085.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 
 - Version 22H2
 - SoftFever version 1.4.1

**Comment by hliebscher** [comment]
it is the same at MAC M1 but not with BBS Printer

and it works if you **set before** walls to 1 and top to zero

i have repeat this 3 times

**Comment by SoftFever** [comment]
Thanks, @rollduck, and @hliebscher .
The fix will be included in the next release
