### ISSUE TITLE
Request: Toolchange gcode

### ISSUE THREAD

**Issue by Prutsium** [SoftFever/BambuStudio-SoftFever#119]
SuperSlicer has a feature we heavy use for Multimaterial (single extruder) printing called Toolchange Gcode under printer settings.
Would it be possible to enable this too in in your version?

![image](https://user-images.githubusercontent.com/42968695/210777197-44e8f6fb-bc44-46e8-a0f0-49ef6b5de149.png)

**Comment by SoftFever** [comment]
It's already there.
It called `Change filament G-code`
![image](https://user-images.githubusercontent.com/103989404/210790155-5db3430a-75af-4f33-9840-279dab4736eb.png)

**Comment by SoftFever** [comment]
Yeah, a lot of variable names have been changed.
I'm starting to add more back-compatible variable names to the fork slowly.
So people can port custom g-code without many hassles.

**Comment by SoftFever** [comment]
Anyway, I'm closing this issue as this is not relevant to the original issue anymore.
