### ISSUE TITLE
The network plugin fails to install

### ISSUE THREAD

**Issue by kvnper** [SoftFever/BambuStudio-SoftFever#12]
The network plugin fails to install when opening the program. It worked OK with v1.3.3 and the official Bambu Studio.

Are there logs somewhere?
![image](https://user-images.githubusercontent.com/47488385/205218413-759184a0-82e9-43ee-aae6-833fdc478234.png)

**Comment by SoftFever** [comment]
It's probably a network glitch.
There is nothing we can do about this. 
If it doesn't work after multiple tries, you will probably find better luck by reporting it to Bambulab instead. 
This closed-sources plugin is not in the scope of this fork.

-SoftFever
