### ISSUE TITLE
after load 3mf the api key (id addr) was not load from conf file

### ISSUE THREAD

**Issue by hliebscher** [SoftFever/BambuStudio-SoftFever#128]
after load 3mf the api key (id addr) was not load from conf file
![api key](https://user-images.githubusercontent.com/9274162/211145659-e447b598-fff3-4fdc-9e7a-d193ca02bedb.jpg)

only if you reload the orange button in printer config
![print settings](https://user-images.githubusercontent.com/9274162/211145682-0748fe46-b250-4d1d-9e08-008c55ebac25.jpg)
![setings ok](https://user-images.githubusercontent.com/9274162/211145685-aad63090-f76f-4b8f-ae06-a2c17a02f1b2.jpg)

**Comment by SoftFever** [comment]
Ah, yes, this is an issue I wanted to fix but always forgot to fix.
Let me see if it's an easy fix
If so, I will squeeze this fix into the release.

**Comment by hliebscher** [comment]
super ! very cool
