### ISSUE TITLE
Save "Arrange all objects" Presets

### ISSUE THREAD

**Issue by eriroh** [SoftFever/BambuStudio-SoftFever#142]
It would be a nice QOL improvement if the state of your "Arrange all objects" settings would be saved for the next session. 

For example, if "Auto rotate for arrangement" is checked, it should be enabled the next time I open the slicer. 

![image](https://user-images.githubusercontent.com/62106991/211205092-aa30adbd-c86a-49c5-add0-5791f25e9f5f.png)

**Comment by SoftFever** [comment]
Make sense

**Comment by eriroh** [comment]
Wonderful implementation. Much appreciated!
