### ISSUE TITLE
Security: .DS_Store files in the Mac app

### ISSUE THREAD

**Issue by Naninani** [SoftFever/BambuStudio-SoftFever#169]
**Describe the bug**
.DS_Store files are included in many dir when the .app is packaged. This is a security issue as .DS_Store files stores custom attributes/metadata of its containing folder and the names of other files around it. Exposing this information could potentially allow hackers to act maliciously and let them see private files.

**To Reproduce**
I used Beyond Compare to compare the both the official Bambu app and SoftFeaver's one.

**Expected behavior**
.DS_Store should be included in the .app.
More: https://buildthis.com/ds_store-files-and-why-you-should-know-about-them/

**Screenshots**
Filtered to show only the added .DS_Store files. 
<img width="314" alt="image" src="https://user-images.githubusercontent.com/1681582/212176920-7a01e61b-654d-496b-906b-b3aeca2dfd06.png">

**Desktop (please complete the following information):**
 - OS: Mac 
 - Version [V1.4.2](https://github.com/SoftFever/BambuStudio-SoftFever/releases/tag/v1.4.2)

**Comment by SoftFever** [comment]
Thanks for the heads up.
It looks like they exist on the git repo. Will delete them

**Comment by SoftFever** [comment]
This change dd1efb3969093bd44fe070644e18018d3f517213 should fix it.
Thanks again.
I'm closing this issue now.
