### ISSUE TITLE
Feature Request to add PrusaSlicer/SuperSlicer 'Label Objects'

### ISSUE THREAD

**Issue by eriroh** [SoftFever/BambuStudio-SoftFever#174]
Would be superb if the 'Label Objects' functionality could be added, so objects can be excluded through mainsail/fluidd/etc. 

![image](https://user-images.githubusercontent.com/62106991/212416422-01f0911c-4535-4eba-9f1a-2008339b2e85.png)

**Comment by sickerin** [comment]
Was this added, hence closed? If not I think it would be good to have. Also from what I recall, the Bambu Studio team does have plans to add options to exclude objects mid print.

**Comment by eriroh** [comment]
I closed this because BambuSoftFever labels objects by default (not sure about the official bambu studio as I've never used it). I just didn't realize that I had my [exclude_objects] in the wrong config.
