### ISSUE TITLE
Switch Timelapse crash BambuStudio

### ISSUE THREAD

**Issue by vr6syncro** [SoftFever/BambuStudio-SoftFever#175]
**Describe the bug**
BambuStudio Crash on switch Timelapse

**To Reproduce**
Open BambuStudio and Switch between Traditionell to Regluar

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win 11
 - Version latest

[Screenshot 2023-01-13 235556](https://user-images.githubusercontent.com/27892314/212433969-e809ccd8-1066-49e2-bcc7-96f54dd80f92.png)

**Comment by SoftFever** [comment]
@vr6syncro this bug should have been fixed in 1.4.2.
Can you check what version are you running?

**Comment by vr6syncro** [comment]
![Screenshot 2023-01-14 171031](https://user-images.githubusercontent.com/27892314/212482272-ba487307-3d3e-4592-a834-d6f5764c60a3.png)

It is the 1.4.2

**Comment by SoftFever** [comment]
A sample project that can repro this issue will be helpful.

**Comment by vr6syncro** [comment]
U can watch a video from the Error: https://www.youtube.com/watch?v=M-NdgMnwUMI
No Project needed.
[log.txt](https://github.com/SoftFever/BambuStudio-SoftFever/files/10428329/log.txt)

**Comment by SoftFever** [comment]
@vr6syncro 
Hmm, I'm not able to repro it.
Can someone help to verify this?

**Comment by vr6syncro** [comment]
> @vr6syncro Hmm, I'm not able to repro it. Can someone help to verify this?

is there anything i can do to get more infos about the crash that might help?

**Comment by MaxKW1** [comment]
I too get this on the latest release here, as well as the normal BStudio with a M1 Mac

**Comment by MaxKW1** [comment]
Here is my project, for me just opening it and then switching the timelapse option to smooth with result in the app closing out. 
[App Crash When Switching to Smooth Timelapse.3mf.zip](https://github.com/SoftFever/BambuStudio-SoftFever/files/10474980/App.Crash.When.Switching.to.Smooth.Timelapse.3mf.zip)

**Comment by kevinpoitra** [comment]
I can reproduce this 100% of the time. For me, it doesn't matter what object I'm printing - I can submit one print and have it switch to the video feed screen without issue, but upon printing any second object (regardless of it being the same object or different), Bambu Studio will crash the moment the timer to switch to the video feed hits 0.

I'm on Pop!_OS 22.04 running version 1.4.2.

**Comment by SoftFever** [comment]
Thanks.
I'm able to reproduce the crash with attached sample project.
PR #224 should fix this issue. 
If you want to help verify the fix, you can download the dev build to try the fix: https://github.com/SoftFever/BambuStudio-SoftFever/actions

**Comment by vr6syncro** [comment]
The latest solve the problem, thank you.
