### ISSUE TITLE
inner-outer-inner/infill seems to be creating some unwated effects

### ISSUE THREAD

**Issue by H4kunaM4tata** [SoftFever/BambuStudio-SoftFever#18]
I couldn't understand why my model out of the blue was showing this weird issue. 

![20221208_112303](https://user-images.githubusercontent.com/35049512/206326646-f0cd7991-e68c-4f96-9aa4-172b6a319cc1.jpg)

After checking the comment https://discord.com/channels/970163353542606888/982154261897019412/1050199936127479918  I went to check my files and found the only thing that was different.
The body has the standard order of wall while the head has the new one released with 1.3.4

![Screenshot 2022-12-08 112030](https://user-images.githubusercontent.com/35049512/206326806-4faf53ad-4bbb-405d-88c7-d99cc779f56e.png)

![Screenshot 2022-12-08 112124](https://user-images.githubusercontent.com/35049512/206326821-e28411db-aec9-4c11-b2a4-277796360f74.png)

I am printing it again with the standard order to confirm.

**Comment by SoftFever** [comment]
Interesting.
What kind of gap fills caused this issue? (those long big gap fills or the tiny gap fills?)

-SoftFever

**Comment by H4kunaM4tata** [comment]
> Interesting. What kind of gap fills caused this issue? (those long big gap fills or the tiny gap fills?)
> 
> -SoftFever

If I understood your question, this is my setup for all the profiles:

![image](https://user-images.githubusercontent.com/35049512/207462917-eafe3f76-a3a6-4f27-9b4f-318450ca1d3e.png)

I haven't done any further tests to make sure I didn't do anything stupid.
But it is fair to mention that another user printing CF had some weird experience with his model showing weird lines not present with the default setting.

I did compare prints' 3MF files with and without the changes, all the ones like Joker, all had the new order while the ones that printed fine, they all had the default order.

**Comment by SoftFever** [comment]
Btw, how many `wall loops` did you use?

**Comment by H4kunaM4tata** [comment]
> Btw, how many `wall loops` did you use?
> 

2 walls and 10% infil, this is my default printing settings for anything non functional or heat resistant.

I need to do further printing tests, I've been busy trying to compile the latest release. No SF related, something changed so some Linux users with me included are "stuck" with the previous slice version.

**Comment by SoftFever** [comment]
> 

This explains.
In the case of two walls, this sandwich mode will degrade to the traditional `outer wall first`.
The outer walls will be printed directly followed by long fast travels, there are chances to cause such artifacts.
This is exactly the reason I implement this new strategy.

-SoftFever

**Comment by H4kunaM4tata** [comment]
I see so that means I must print with 3 walls always?!

**Comment by SoftFever** [comment]
That's right.

**Comment by SoftFever** [comment]
I will close this issue as this is not a sandwich mode issue anymore.
Free feel to create a new issue if you found the issue persists with 3+ wall loops.

-SoftFever

**Comment by H4kunaM4tata** [comment]
It seems to be fine so far, I just printer a cube at 0.32
Will keep monitoring things closer.
It is fair to close it.
Thank you for checking this out.

![image](https://user-images.githubusercontent.com/35049512/208356797-4e8aa22a-6697-450e-b98e-c5a95f66c2e6.png)

**Comment by SoftFever** [comment]
> It seems to be fine so far, I just printer a cube at 0.32 Will keep monitoring things closer. It is fair to close it. Thank you for checking this out.
> 
> ![image](https://user-images.githubusercontent.com/35049512/208356797-4e8aa22a-6697-450e-b98e-c5a95f66c2e6.png)

Cool! Keep us posted with your new testing.
I've received very positive feedback for the sandwich mode.
The following image is provided by a user: 
Sandwich vs inner-outer-infill.
![image](https://user-images.githubusercontent.com/103989404/208391627-bbef25de-1a27-44c9-a2ca-99400bf52989.png)

Although I don't really recommend printing such models with sandwich mode.
It's meant for those engineering parts. But still, I'm very glad to see it works well for this kind of model too.

-SoftFever

**Comment by beaverdude** [comment]
Hello! I bumped into this issue searching for explanation of a very surprising behavior when using sandwich wall mode. 

It looks like a border case when the 3rd line in sandwich is actually a little gap to be filled. After that gap the nozzle jumps to external line somewhat underprimed. 
@Funkton and @SoftFever  mentioned gaps fill in this thread

![Image](https://github.com/user-attachments/assets/fbe0c644-8e04-4911-80bf-47f17a987d0b)

![Image](https://github.com/user-attachments/assets/093f69c3-aad4-41f1-94d9-ee518aea5d89)

[sandwich_artefact_PLA_7m28s.zip](https://github.com/user-attachments/files/20351688/sandwich_artefact_PLA_7m28s.zip)
