### ISSUE TITLE
Allow setting bed temperature to >120C

### ISSUE THREAD

**Issue by antonme** [SoftFever/BambuStudio-SoftFever#183]
**Is your feature request related to a problem? Please describe.**
Right now you can't set bed temperature to a value higher than 120C for any printer (even when your printer does supports it)

**Describe the solution you'd like**
Allow setting bed temp >120 or some new setting to set each printer's limit

**Describe alternatives you've considered**
Right now I had to overwrite printer's start gcode sequence to set temp manually

**Comment by SoftFever** [comment]
will raise the limit to 300 in next update

**Comment by SoftFever** [comment]
Fixed in f9200cc7e4fba7a975a707a320100ddea014368b

**Comment by antonme** [comment]
Wow, that was fast! Thank you

**Comment by hliebscher** [comment]
> antonme

can you close the request?
