### ISSUE TITLE
Icon switches colors on MacOS  (cosmetic bug)

### ISSUE THREAD

**Issue by psiberfunk** [SoftFever/BambuStudio-SoftFever#187]
**Describe the bug**
On macos, during application launch the app icon in the Dock has the correct new color scheme (teal), but switches to the old green color after launching.

During launch :  
<img width="57" alt="Screenshot 2023-01-17 at 10 17 49 AM" src="https://user-images.githubusercontent.com/19777571/212937496-445032f1-11d9-4ef6-b9f9-e775c6d1b83c.png">

After Launch, you see this:
<img width="57" alt="Screenshot 2023-01-17 at 10 17 57 AM" src="https://user-images.githubusercontent.com/19777571/212937626-e3186ed5-9b9d-46f9-a963-32af506678b9.png">

Mac OS only, as far as I can tell.  Running intel/x86 version.

**Comment by hliebscher** [comment]
i am looking also for button slice plate and sen g-code ;-)

**Comment by SoftFever** [comment]
Has the fix ready locally :)
Will push the fix later.

**Comment by hliebscher** [comment]
ok

**Comment by psiberfunk** [comment]
> ok

you seem to be commenting on the wrong issue.. perhaps thats why you're confused?

**Comment by IkarusX1978** [comment]
same issue here ...
concerns even Intel and Sillicon Mac!

**Comment by hliebscher** [comment]
> > ok
> 
> you seem to be commenting on the wrong issue.. perhaps thats why you're confused?
i had fixt this with pa but to late  SoftFever has fix locally  ...

**Comment by hliebscher** [comment]
@psiberfunk can you close ? its fixed
