### ISSUE TITLE
Wiki for PA tower is misleading:  Needs update to tell bowden users to use different multiplier

### ISSUE THREAD

**Issue by psiberfunk** [SoftFever/BambuStudio-SoftFever#189]
The wiki here: https://github.com/SoftFever/BambuStudio-SoftFever/wiki/Calibration describing the calibration process for the PA tower tells users to use 0.002 for the tower.  But this is incorrect for bowden tower users.  I think they should be using a much larger value.. I looked at the gcode and think it's 0.02 instead, but i'm not sure?

In any case, the wiki should note that bowden users need a different value.

**Comment by SoftFever** [comment]
Fixed.
Thanks.
