### ISSUE TITLE
Feature Request: Add print area min/max support for bed mesh macros.

### ISSUE THREAD

**Issue by screech24** [SoftFever/BambuStudio-SoftFever#194]
[Superslicer] has Print area Min/Max options that help to reduce the amount of probing points needed when doing a bed mesh. see attached. example of Klipper macro used in Superslicer. 
BED_MESH_CALIBRATE AREA_START={first_layer_print_min[0]},{first_layer_print_min[1]} AREA_END={first_layer_print_max[0]},{first_layer_print_max[1]}

here is the link to the klipper/ slicer install guide for print area only macro. 
[https://gist.github.com/ChipCE/95fdbd3c2f3a064397f9610f915f7d02](url)

This would also be incredible to add to Bambu printers but i assume this would also needed to be added at a firmware level for that to work.

**Comment by hliebscher** [comment]
It works with bambustudio

**Comment by screech24** [comment]
> It works with bambustudio

its not working for me with a 3rd party printer running klipper using the provided macro in Superslicer start G-code. 

so i'm not sure what i'm doing wrong then?

**Comment by hliebscher** [comment]
i use this M557 X{first_layer_print_min[0]}:{first_layer_print_max[0]} Y{first_layer_print_min[1]}:{first_layer_print_max[1]} S25

**Comment by SoftFever** [comment]
@screech24 It is supported.
You can ref the start g-code in the built-in Voron profile I provided.
![image](https://user-images.githubusercontent.com/103989404/213449701-129daf3b-8a2c-476b-918c-5b4d8cc06044.png)

**Comment by screech24** [comment]
> @screech24 It is supported. You can ref the start g-code in the built-in Voron profile I provided. ![image](https://user-images.githubusercontent.com/103989404/213449701-129daf3b-8a2c-476b-918c-5b4d8cc06044.png)

would this mean i need to modify the macro used in klipper then as well, as it currently uses AREA_START & AREA_END variables.
