### ISSUE TITLE
Big Fan is not enabled after layer 1

### ISSUE THREAD

**Issue by VexAzomi** [SoftFever/BambuStudio-SoftFever#199]
As the title says, I noticed, that the big cooling fan (P2) is not enabled after layer 1.
I traced down the bug to be a missing line in the gcode.
As far as I am aware, the only setting for the big fan (P2) can be made in the filament cooling section.
If I am wrong, please correct me. However here are the relevant lines of two gcodes:

This is the official slicer:
M106 S252.45
M106 P2 S204
; CHANGE_LAYER
; Z_HEIGHT: 0.4
; LAYER_HEIGHT: 0.2
G1 E-.56 F1800
; WIPE_START
G1 F24000
........

This is from softfever:
M106 S252.45 ; enable fan
; CHANGE_LAYER
; Z_HEIGHT: 0.4
; LAYER_HEIGHT: 0.2
G1 E-.56 F1800 ; retract
; WIPE_START
G1 F24000
........

**Comment by hliebscher** [comment]
witch printer ? have you enable aux fan in printer Config?

**Comment by tripp396** [comment]
I am seeing this on my P1P and newly installed and confirmed working fan. Definitely goes for the first layer then shuts off. Filament cooling on that profile has aux fan set to 70%.

**Comment by VexAzomi** [comment]
Dammit, I am sorry. Tried to note everything important but my brain is stupid.
Okay, so I am printing on the P1P with the textured sheet. I made a copy of the BBL PLA filament config and the 0.2mm standard settings. What Printer config are you referring to?

**Comment by tripp396** [comment]
For me it is the following profiles, all stock:

Printer: Bambu Lab P1P 0.4 nozzle
Filament: Bambu PLA Basic
Process: 0.16 Optimal @BBL P1P (only change here is supports added and a different top pattern)

**Comment by VexAzomi** [comment]
tripp396, can you explain what you are experiencing? I dont really get what you mean by "Definitely goes for the first layer then shuts off"

**Comment by tripp396** [comment]
> 

Sure. The auxiliary fan will blow air for the first layer of the print. Then all subsequent layers the auxiliary fan will not run at all.

**Comment by VexAzomi** [comment]
Äh, did you turn off the function disable fans for the first layer?
Because... the fan is supposed to do the opposite or not?

**Comment by tripp396** [comment]
I did not enable that. I could enable and see if its working in reverse. I'll have to see what my schedule looks like today for that test.

I'm not sure its that because the only fan not working is the big part cooling fan (the free gift one). Not the part cooling one on the print head.

**Comment by VexAzomi** [comment]
So uhm I found the setting panel hliebscher was referring to. So many new buttons with this program.. I did not notice, that there was a button 
![image](https://user-images.githubusercontent.com/123071956/213504437-067c3670-70a0-4971-802c-058dd367dc75.png)
After enabling that, everything works now, so I am going to close this issue.

**Comment by tripp396** [comment]
> So uhm I found the setting panel hliebscher was referring to. So many new buttons with this program.. I did not notice, that there was a button ![image](https://user-images.githubusercontent.com/123071956/213504437-067c3670-70a0-4971-802c-058dd367dc75.png) After enabling that, everything works now, so I am going to close this issue.

Well I feel like an idiot. I thought I looked through there like 5 times.

**Comment by VexAzomi** [comment]
Yep, I feel like an idiot for opening an issue here. But hey, if its working for you aswell... hurray!

**Comment by CCS86** [comment]
I still think there is an issue here with the default printer profile not having the AUX fan enabled. You can save a user preset of the machine with it turned on, but you really shouldn't have to.
