### ISSUE TITLE
Flow on Print Settings

### ISSUE THREAD

**Issue by tommy536** [SoftFever/BambuStudio-SoftFever#200]
Hello,

in the print settings, there is a flow value for first and top layer. How is this calculated? Is this a standalone flow setting or a multi of the base filament flow setting?

For example. If i use 0.96 flow in the filament setting and in the print Setting is 1.0 for top layer set, is 1.0 = 0.96 or really 1.0?

**Comment by hliebscher** [comment]
the flow setting in filament is the factor for all extrusion so is it in your case 1 =  0.96

**Comment by SoftFever** [comment]
It's a multi of the base filament flow setting.

**Comment by tommy536** [comment]
Ok thanks! Softfever is a great Alternative to SS. Good Job!
