### ISSUE TITLE
no Bed Type  to choice.

### ISSUE THREAD

**Issue by goldjunge91** [SoftFever/BambuStudio-SoftFever#208]
Hi,
in the official BambuStudio version I can choice between, all Bambu build plates, but on your version not, are this not implemented on your version ?
I added my anycubic i3 mega s profile to your anycubic max profile and added it as zip file.
and any idea how I can add plates ? and add to different plates custom settings would be great.
I'm not sure that its a Bug or Feature request.

<img width="1377" alt="Bildschirm­foto 2023-01-21 um 23 11 39" src="https://user-images.githubusercontent.com/30201929/213889051-5d617304-83dc-44d6-9324-934c6fe60d3d.png">
<img width="1384" alt="Bildschirm­foto 2023-01-21 um 23 12 42" src="https://user-images.githubusercontent.com/30201929/213889057-f4621170-481f-4440-aa7a-67d612b25810.png">
[SoftFever.zip](https://github.com/SoftFever/BambuStudio-SoftFever/files/10473186/SoftFever.zip)

**Comment by SoftFever** [comment]
It is per design.
As far as I know, no third-party printers use different types of beds.
They also tend to introduce more user errors so I disabled it.

**Comment by goldjunge91** [comment]
alright how can I enable it ? where I have to search in the code for it. I have differents plate and love to use the function

**Comment by SoftFever** [comment]
I can’t remember the exact place. You can search through the commit history with keyword ’bed’Sent from my iPhoneOn 22 Jan 2023, at 9:33 PM, Goldjunge91 ***@***.***> wrote:﻿
alright how can I enable it ? where I have to search in the code for it. I have differents plate and love to use the function
