### ISSUE TITLE
Support Video Feed on Linux for BambuLab Printer

### ISSUE THREAD

**Issue by SebiPanther** [SoftFever/BambuStudio-SoftFever#213]
**Is your feature request related to a problem? Please describe.**
If you try to start the video feed of a BambuLab Printer on Linux this error message appear:
![grafik](https://user-images.githubusercontent.com/9606697/213909140-7ad5e6ec-6d24-4969-9ed0-c2a5fb8c0949.png)

**Describe the solution you'd like**
This solves it: https://github.com/bambulab/BambuStudio/pull/1045
Maybe if you update your fork and do a new release its already fixed.

**Describe alternatives you've considered**
Update the fork from this source directly: https://github.com/jwise/BambuStudio/tree/jwise/x1-video-linux

**Additional context**
- OS: Ubuntu Mate 22.10
- Version V1.4.2

Thanks for the good work!

**Comment by SoftFever** [comment]
It's merged.
You can test it with the nightly build here: https://github.com/SoftFever/BambuStudio-SoftFever/actions/runs/3977966683

**Comment by SebiPanther** [comment]
Yes - it works - thank you! \o/
![grafik](https://user-images.githubusercontent.com/9606697/213933872-0252f9cd-5034-4e01-9d29-dafee21fc2b5.png)
Sidenote: I had to install a something, but the Warned me about it:
![grafik](https://user-images.githubusercontent.com/9606697/213933861-ce37221c-0947-424f-be8b-771b40f3e98a.png)
I just did this and it worked well: `sudo apt-get install gstreamer1.0-plugins-bad gstreamer1.0-plugins-bad-apps`
