### ISSUE TITLE
Unable to set layer height to .3 using .4 nozzle

### ISSUE THREAD

**Issue by feistyknitty** [SoftFever/BambuStudio-SoftFever#217]
**Describe the bug**
Found in 1.4.2: 

There are designs (specifically "string art" designs from 3DPrintbunny) which require a layer height of .3. I have been able to use this layer height with .4 nozzle with no issues on multiple printers, including the BBL X1. Bambu Studio from BBL allows me to set .3 layer height with no issue. 

SoftFever branch gives me an error, and automatically resets layer height to .28. It does not allow me to override this. As this does not seem to be something that could cause harm to hardware (maybe just produce prints that aren't great quality if someone tries it without adjusting settings), I feel the user should be allowed to override this if they desire. 

Many sources on a Google search indicate that .32 is an acceptable max layer height for a .4 nozzle (e.g. https://3dsolved.com/best-layer-height-for-3d-printing/). I understand that with the speed of the Bambu, having a thicker layer height could cause issues with volumetric speed. If that is a concern, perhaps displaying an alert to the user about potential issues would be advisable, but preventing users from using a setting that **should** be usable is a poor user experience.

**3mf File for This Bug**
N/A

**To Reproduce**
1. Go to 'Quality'
2. Click on 'Layer height'
3. Change field contents to ".3"

**Expected behavior**
Layer heights up to potentially .32 should be allowed. For BBL printers, perhaps an alert that a high layer height could cause issues at high speeds could be helpful, but user should not be prevented from setting a layer height that is acceptable for printing with the selected nozzle.

**Screenshots**
<img width="779" alt="Screen Shot 2023-01-22 at 10 46 40 AM" src="https://user-images.githubusercontent.com/29808159/213934587-601f53eb-5694-41f8-8b96-dd668d5ca726.png">

**Desktop (please complete the following information):**
 - OS: MacOS Monterey 
 - Version 12.4

**Comment by hliebscher** [comment]
this is in your pinter settings under extruder!  pls change max from 0.28 to 0.32 than it works 
is not a bug ! its a feature

**Comment by SoftFever** [comment]
@feistyknitty 
As @hliebscher mentioned, you can change the max layer height in extruder tab
![image](https://user-images.githubusercontent.com/103989404/213957882-06af1dfe-ac6c-4a8b-8c66-daf886f48155.png)

**Comment by feistyknitty** [comment]
Ah, thank you! I didn't realize this was a setting that could be changed. When I got the error on SoftFever and not main Bambu, I thought it was something specific to the branch. I do still find it odd that the default between the two is different, though!
