### ISSUE TITLE
Software doesnt work on Windows. Shows just whats on my Harddisk

### ISSUE THREAD

**Issue by zeroemso** [SoftFever/BambuStudio-SoftFever#24]
**Describe the bug**
If i download the latest version and start the bambu-studio.exe
it shows only my Harddisk folders.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10
![2022-12-12_21h42_19](https://user-images.githubusercontent.com/111010928/207154631-36220fde-51f5-4e71-a30e-928ce1bdcf18.jpg)

**Comment by zeroemso** [comment]
got it working. didnt found the info that you have to copy all files to your existing folder.

**Comment by Hawxxer** [comment]
Can you elaborate same problem, what existing folder?

**Comment by Hawxxer** [comment]
Found the issue! no special characters in the path file of the application, please reopen this issue here.
