### ISSUE TITLE
Media playback error: No URL-handler implemented for "bambu" in Ubuntu 22.10

### ISSUE THREAD

**Issue by RobRobM** [SoftFever/BambuStudio-SoftFever#240]
**Describe the bug**
When pressing the play button on the Device Tab the message Media playback error: No URL-handler implemented for "bambu" displays and the camera feed does not work

**To Reproduce**
1. Go to Device tab
2. Click on the play button

**Expected behavior**
The camera feed should start.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 22.10

**Comment by SoftFever** [comment]
The latest 1.4.3 version should have the video now.

**Comment by RobRobM** [comment]
720p works! With 1080p resolution I only get a black screen. And the default settings is 1080p. So to get the camera working I had to switch to 720p and restart the stream to get it working.

Great work by the way. This project is the reason I bought the X1C!!! 

Thanks for all your hard work!!!!!
