### ISSUE TITLE
SoftFever 1.4.3- MAC OS launch with errors

### ISSUE THREAD

**Issue by christianjou** [SoftFever/BambuStudio-SoftFever#243]
**Describe the bug**
When i launch SoftFever 1.4.3 there is some errors and it halts

**To Reproduce**
1. JUST LAUNCH

**Screenshots**
<img width="949" alt="Capture d’écran 2023-01-27 à 17 29 13" src="https://user-images.githubusercontent.com/72012052/215140196-c429cfc7-e95d-43da-8e6d-6805e7c3a9e3.png">

Full text errors : 

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               BambuStudio [10025]
Path:                  /Users/USER/Downloads/BambuStudio-SoftFever 3.app/Contents/MacOS/BambuStudio
Identifier:            com.bambulab.bambu-studio
Version:               01.04.02.13 (???)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-01-27 17:25:44.1916 +0100
OS Version:            macOS 12.6.3 (21G419)
Report Version:        12
Bridge OS Version:     3.0 (14Y910)
Anonymous UUID:        83E42FDE-A5FA-6BF6-F29A-D22600391A91

Sleep/Wake UUID:       41E6A0B7-07E2-4E19-9694-99C057F3BB73

Time Awake Since Boot: 25000 seconds
Time Since Wake:       1033 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: '/usr/local/opt/zstd/lib/libzstd.1.dylib'
Referenced from: '/Users/USER/Downloads/BambuStudio-SoftFever 3.app/Contents/MacOS/BambuStudio'
Reason: tried: '/usr/local/opt/zstd/lib/libzstd.1.dylib' (no such file), '' (no such file), '' (no such file)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	       0x112c6a98e __abort_with_payload + 10
1   dyld                          	       0x112c80a72 abort_with_payload_wrapper_internal + 80
2   dyld                          	       0x112c80aa4 abort_with_payload + 9
3   dyld                          	       0x112c2e699 dyld4::halt(char const*) + 615
4   dyld                          	       0x112c2a5b5 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3995
5   dyld                          	       0x112c294e4 start + 388

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000002000209  rbx: 0x0000000000000000  rcx: 0x00007ff7b707f538  rdx: 0x00007ff7b707f9a0
  rdi: 0x0000000000000006  rsi: 0x0000000000000001  rbp: 0x00007ff7b707f580  rsp: 0x00007ff7b707f538
   r8: 0x00007ff7b707f5a0   r9: 0x0000000000000000  r10: 0x0000000000000093  r11: 0x0000000000000246
  r12: 0x0000000000000093  r13: 0x00007ff7b707f9a0  r14: 0x0000000000000001  r15: 0x0000000000000006
  rip: 0x0000000112c6a98e  rfl: 0x0000000000000246  cr2: 0x0000000112c30da4
  
Logical CPU:     0
Error Code:      0x02000209 
Trap Number:     133

Binary Images:
       0x112c24000 -        0x112c8ffff dyld (*) <006a3e6f-3cd3-34d9-b0f2-ed6bd67a95a6> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=80.1M resident=0K(0%) swapped_out_or_unallocated=80.1M(100%)
Writable regions: Total=9524K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9524K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
VM_ALLOCATE                         12K        3 
__DATA                             912K        3 
__DATA_CONST                      2080K        2 
__LINKEDIT                        23.3M        4 
__TEXT                            56.8M        2 
dyld private memory               1024K        1 
===========                     =======  ======= 
TOTAL                            148.1M       17 

-----------
Full Report
-----------

{"app_name":"BambuStudio","timestamp":"2023-01-27 17:25:44.00 +0100","app_version":"01.04.02.13","slice_uuid":"12e6b36f-0df9-36bb-9ced-1a4a7f88d37f","build_version":"","platform":1,"bundleID":"com.bambulab.bambu-studio","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.6.3 (21G419)","incident_id":"C3880314-EA08-48A5-BC40-5F7FA8FAF92E","name":"BambuStudio"}
{
  "uptime" : 25000,
  "procLaunch" : "2023-01-27 17:25:44.1597 +0100",
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro13,2",
  "procStartAbsTime" : 25020340371794,
  "coalitionID" : 7095,
  "osVersion" : {
    "train" : "macOS 12.6.3",
    "build" : "21G419",
    "releaseType" : "User"
  },
  "captureTime" : "2023-01-27 17:25:44.1916 +0100",
  "incident" : "C3880314-EA08-48A5-BC40-5F7FA8FAF92E",
  "bug_type" : "309",
  "pid" : 10025,
  "procExitAbsTime" : 25020367546304,
  "cpuType" : "X86-64",
  "procName" : "BambuStudio",
  "procPath" : "\/Users\/USER\/Downloads\/BambuStudio-SoftFever 3.app\/Contents\/MacOS\/BambuStudio",
  "bundleInfo" : {"CFBundleShortVersionString":"01.04.02.13","CFBundleIdentifier":"com.bambulab.bambu-studio"},
  "storeInfo" : {"deviceIdentifierForVendor":"6DA8EC19-5EC3-5740-A933-EA0BF694C826","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.bambulab.bambu-studio",
  "crashReporterKey" : "83E42FDE-A5FA-6BF6-F29A-D22600391A91",
  "wakeTime" : 1033,
  "bridgeVersion" : {"build":"14Y910","train":"3.0"},
  "sleepWakeUUID" : "41E6A0B7-07E2-4E19-9694-99C057F3BB73",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: '\/usr\/local\/opt\/zstd\/lib\/libzstd.1.dylib'","Referenced from: '\/Users\/USER\/Downloads\/BambuStudio-SoftFever 3.app\/Contents\/MacOS\/BambuStudio'","Reason: tried: '\/usr\/local\/opt\/zstd\/lib\/libzstd.1.dylib' (no such file), '' (no such file), '' (no such file)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":290519,"threadState":{"r13":{"value":140701904402848},"rax":{"value":33554953},"rflags":{"value":582},"cpu":{"value":0},"r14":{"value":1},"rsi":{"value":1},"r8":{"value":140701904401824},"cr2":{"value":4609740196},"rdx":{"value":140701904402848},"r10":{"value":147},"r9":{"value":0},"r15":{"value":6},"rbx":{"value":0},"trap":{"value":133},"err":{"value":33554953},"r11":{"value":582},"rip":{"value":4609976718,"matchesCrashFrame":1},"rbp":{"value":140701904401792},"rsp":{"value":140701904401720},"r12":{"value":147},"rcx":{"value":140701904401720},"flavor":"x86_THREAD_STATE","rdi":{"value":6}},"frames":[{"imageOffset":289166,"symbol":"__abort_with_payload","symbolLocation":10,"imageIndex":0},{"imageOffset":379506,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":80,"imageIndex":0},{"imageOffset":379556,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":0},{"imageOffset":42649,"symbol":"dyld4::halt(char const*)","symbolLocation":615,"imageIndex":0},{"imageOffset":26037,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3995,"imageIndex":0},{"imageOffset":21732,"symbol":"start","symbolLocation":388,"imageIndex":0}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 4609687552,
    "size" : 442368,
    "uuid" : "006a3e6f-3cd3-34d9-b0f2-ed6bd67a95a6",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 140703385894912,
  "size" : 19331678208,
  "uuid" : "b6d97ead-9d19-3228-adaa-cca8452c02d2"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=80.1M resident=0K(0%) swapped_out_or_unallocated=80.1M(100%)\nWritable regions: Total=9524K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9524K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                         12K        3 \n__DATA                             912K        3 \n__DATA_CONST                      2080K        2 \n__LINKEDIT                        23.3M        4 \n__TEXT                            56.8M        2 \ndyld private memory               1024K        1 \n===========                     =======  ======= \nTOTAL                            148.1M       17 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6112e14f37f5d11121dcd519",
      "factorPackIds" : {
        "SIRI_TEXT_TO_SPEECH" : "634710168e8be655c1316aaa"
      },
      "deploymentId" : 240000231
    },
    {
      "rolloutId" : "60f8ddccefea4203d95cbeef",
      "factorPackIds" : {

      },
      "deploymentId" : 240000021
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro13,2, BootROM 499.40.2.0.0, 2 processors, Dual-Core Intel Core i5, 2,9 GHz, 8 GB, SMC 2.37f25
Graphics: Intel Iris Graphics 550, Intel Iris Graphics 550, Built-In
Display: Color LCD, 2560 x 1600 Retina, Main, MirrorOff, Online
Memory Module: BANK 0/DIMM0, 4 GB, LPDDR3, 2133 MHz, 0x80CE, 0x4B3445364533303445422D45474347202020
Memory Module: BANK 1/DIMM0, 4 GB, LPDDR3, 2133 MHz, 0x80CE, 0x4B3445364533303445422D45474347202020
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x157), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1710.4)
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB30Bus
USB Device: Apple T1 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 41.5
Thunderbolt Bus: MacBook Pro, Apple Inc., 41.5

**Desktop (please complete the following information):**
 - OS:  MONTEREY
 -  - Version 12.6.3

**Comment by hliebscher** [comment]
@SoftFever 
Mac M1 (arm64) is working
the x86_64 version from github has the bug
my own self build version 1.4.3 is working.

**Comment by Manfredo1952** [comment]
@SoftFever  @hliebscher 
My Intel-Version is starting flawless. No  problems.

**Comment by Manfredo1952** [comment]
Error report says "
![image](https://user-images.githubusercontent.com/56330568/215230255-7c2351ef-77bf-4bf5-b40f-b046d500c8d4.png)

**Comment by SoftFever** [comment]
An error with the host runner's dependency was identified in the CI/CD build.
A new build has been uploaded to correct the issue.
Please download the updated build from the release page.

**Comment by christianjou** [comment]
All is perfect now. Thanks.

**Comment by hliebscher** [comment]
@christianjou pls close the issue if is fine

**Comment by christianjou** [comment]
done
