### ISSUE TITLE
PA Calibration Tower Method does not work

### ISSUE THREAD

**Issue by Theos88** [SoftFever/BambuStudio-SoftFever#246]
**Describe the bug**
The PA Calibration Tower Method does not work in my case. It seems to print with one fix value the whole print through. In V1.4.2 it works just fine as intended.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Version [1.4.3]
 - Printer: BBL X1C

**Comment by Theos88** [comment]
Hi,

the PA Calibration Tower Method does not work in my case. It seems to print with one fix value the whole print through. In V1.4.2 it works just fine as intended. Do you need further input? I didn´t test the Line Method.

**Comment by hliebscher** [comment]
for Mac it works 
;AFTER_LAYER_CHANGE
;45
**M572 D0 S0.09; Override pressure advance value**
; printing object tower_with_seam.stl id:0 copy 0
M204 P800 ; adjust acceleration

**Comment by Theos88** [comment]
I´ll post the gcode later. Only difference I noticed so far is, that my gcode uses M900 Linear Advance instead of M572 Pressure Advance.

**Comment by hliebscher** [comment]
@Theos88   M572 is for my Printer MARLIN needs M900 with growing up parameters each line

**Comment by SoftFever** [comment]
@Theos88 
Confirmed, it was a bug.
Switch to line mode then switch back to tower mode in the PA dialog will fix it.
I will release a hotfix soon

**Comment by Theos88** [comment]
Ok, thank you!

**Comment by SoftFever** [comment]
Thanks for reporting the bug.
The problem has been resolved in the latest hotfix release.

**Comment by ryguyy46** [comment]
I’m having the same issue. PA Tower seems to print with the same value, I tired using line and and all of them looked exactly the same. Even tried switching back and forth from line to tower. Same results.

**Comment by gamelover42** [comment]
I just sliced and printed the PA tower using v1.6.3 and the corners are identical all the way up.
