### ISSUE TITLE
LED Lights

### ISSUE THREAD

**Issue by Highlander-bdj** [SoftFever/BambuStudio-SoftFever#247]
The P1P start GCODE contains code to turn on the LEDs: M960 S5 P1 ; turn on logo lamp

Would you add code to the end GCODE to turn them off?

**Comment by hliebscher** [comment]
M960 S5 P0/1 | Bambu Lab toolhead logo light off/on

@Highlander-bdj  pls add yourself the code M960 S5 P0 to your END CODE

**Comment by Highlander-bdj** [comment]
Thank you for that. Would you consider incorporating it into the default. end code since the on is already there?  I know it’s minor but doing it myself makes me have to create a custom profile.

**Comment by hliebscher** [comment]
@Highlander-bdj pls send me the tested END GCODE i make a PR for the Profile

**Comment by hliebscher** [comment]
@Highlander-bdj can you close the bug if you fix this?

**Comment by Highlander-bdj** [comment]
I thought I did?
