### ISSUE TITLE
Brim function is broken

### ISSUE THREAD

**Issue by YyAoMmIi** [SoftFever/BambuStudio-SoftFever#256]
![image](https://user-images.githubusercontent.com/58763731/215305802-cf10923e-3057-4eb8-a5a1-9b16af4baeaa.png)

This is certainly more than 3mm. i tested with outer only, and still get the issue. inner only did not brim anything at all.
Also, this brim is weird since a brim should not overlap the 1st layer, but it does so here. 

this issues is also present in today's hotfix

**Comment by hliebscher** [comment]
for me it works at MAC M1
![dragon](https://user-images.githubusercontent.com/9274162/215330902-25beb283-6fc2-431e-8c4a-4ad7d766c6ac.jpg)

**Comment by hliebscher** [comment]
@YyAoMmIi  can you send the model or a link?

**Comment by YyAoMmIi** [comment]
https://www.myminifactory.com/object/3d-print-flexi-print-in-place-imperial-dragon-218337

**Comment by hliebscher** [comment]
pls send your 3mf file with settings with 1.4.4 works

**Comment by hliebscher** [comment]
@YyAoMmIi can you close the bug if this works?

**Comment by YyAoMmIi** [comment]
I had had sent the file to softfever on discord since I didn't have a way
to contact you privately .
I think the issue is more when there multiple plate. when i was printing
from plate 1-11 it was fine, but plate 12 and it broke.
