### ISSUE TITLE
Change Flow calibration object shape.

### ISSUE THREAD

**Issue by randyre** [SoftFever/BambuStudio-SoftFever#263]
Noticed you have a flow object that has a circular ring on it but it's not being used, could we use that object as well as make holes off to the sides? 

A smooth flat surface is great for making sure that a smooth flat surface can be printed, but would be nice to make sure that a flat surface with other features also prints well. 

![Cal Shapes](https://user-images.githubusercontent.com/60475095/215350477-5bb0fa43-6038-4ffe-832b-54fe7ab1e5b9.jpg)

**Comment by hliebscher** [comment]
pls send the STEP file not STL

**Comment by SoftFever** [comment]
I haven't found the circle to be useful in my testing.

As a model designed for flow rate calibration, it shouldn't be tested for anything else.
It will remain unchanged hence.

**Comment by randyre** [comment]
This is mainly a silk filament issue, but the start and stop of flow, especially on flat surfaces where there is a perimeter or two have a bad ghosting effect that seems to be caused by unequal flow changing the shine of the filament.  I'll attach an example.  

I know it's an extreme use case, but if we either could add it as an alternate flow test or tell me how I can replace the object myself it would be appreciated.
![Photo Jan 31 2023, 11 34 33](https://user-images.githubusercontent.com/60475095/215838933-cabd6538-3412-4199-a285-59c35fcec8da.jpg)

**Comment by SoftFever** [comment]
> 

IMHO this is not a flow issue.
I suggest reducing the speed of silk filaments.

You are welcome to create a post in [Discuss](https://github.com/SoftFever/BambuStudio-SoftFever/discussions)
I'm closing this issue
