### ISSUE TITLE
[Typo] Readme.MD

### ISSUE THREAD

**Issue by psiberfunk** [SoftFever/BambuStudio-SoftFever#27]
![image](https://user-images.githubusercontent.com/19777571/207407987-216aeebf-c985-43b2-a5e5-e989df5c5cd4.png)

Should read "macro"

**Comment by psiberfunk** [comment]
Yes, I know it's a nitpick.. sorry i'm a spelling nazi

**Comment by SoftFever** [comment]
Corrected in https://github.com/SoftFever/BambuStudio-SoftFever/commit/c06190b79c0ba8861ab387da9f68c5ca6d1adb15

Not at all.
I appreciate the help :)

-SoftFever
