### ISSUE TITLE
[Feature Request] Specific fan at layer

### ISSUE THREAD

**Issue by GiaPag** [SoftFever/BambuStudio-SoftFever#28]
It would be nice to be able to decide the fan speed in certain layers.
I've only seen such an option on IdeaMaker
this is an example
![Screenshot 2022-12-14 alle 09 18 08](https://user-images.githubusercontent.com/120025021/207542644-d91d0a97-fb6d-4be5-bc0d-fac82cf965b7.png)
This function is very useful in order not to have a forced fan at a higher speed for the entire print. In difficult pieces it helps a lot for overhangs and also avoids making a piece more fragile having avoided a bigger fan for the whole print.
By this I am referring to technical sections where, for example, in some areas we find difficult overhangs but we have few walls

**Comment by SoftFever** [comment]
I would argue that with the gradient overhang speed we have in the slicer, this is not needed anymore.
<img width="395" alt="Screenshot 2022-12-14 at 10 43 00 PM" src="https://user-images.githubusercontent.com/103989404/207626690-0c3fb3c2-a68c-4492-bd76-65ece915fb53.png">

**Comment by GiaPag** [comment]
Hi, yes but it's not the same thing instead to the possibility to specific fan speed at layer

**Comment by SoftFever** [comment]
Given the limited time I can spend on this fork, we won't have this feature in the near future.
Unless there someone volunteered to work on this.

I am closing it.

**Comment by GiaPag** [comment]
I see, thanks anyway
