### ISSUE TITLE
Spiral Vase mode crashes Bambu Studio

### ISSUE THREAD

**Issue by Fl0ken** [SoftFever/BambuStudio-SoftFever#294]
**Describe the bug**
Loading in any file (STLs) that should be in vase mode and then clicking Spiral vase crashes the application

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
1. Load file
2. Click on Spiral Vase
3. See error

**Expected behavior**
Bambu Studio slices the file

**Screenshots**
Error Code: 
20:16:54: BambuStudio got an unhandled exception: boost::bad_any_cast: failed conversion using boost::any_cast
20:16:54: BambuStudio got an unhandled exception: boost::bad_any_cast: failed conversion using boost::any_cast

**Desktop (please complete the following information):**
 - Windows 10
 - 21H2
 - BambuStudio SoftFever 1.4.4

**Comment by hliebscher** [comment]
As a workaround, you can switch timelapse to smooth first before ticking the Spiral vase mode.

we have fixed thisin next version

**Comment by Fl0ken** [comment]
Version is 1.4.4
Smooth timelapse works, but the prime tower needs to be enabled, otherwise it's crashing.

**Comment by hliebscher** [comment]
you have to compile yourself or wait for the next 1.4.5 
we have fixt this

![fix](https://user-images.githubusercontent.com/9274162/217909932-c2ff6f3c-97d6-41dc-89c0-6f70e4e5c4d3.jpg)
