### ISSUE TITLE
Overhang speed is not respected on painted/coloured parts

### ISSUE THREAD

**Issue by rovili** [SoftFever/BambuStudio-SoftFever#296]
**Describe the bug**
Overhang speed is not respected on painted/coloured parts

**To Reproduce**
Take a part with overhang and color the overhang

**Expected behavior**
Overhang speed should also be applied on coloured parts

**Screenshots**
With different color:
<img width="667" alt="image" src="https://user-images.githubusercontent.com/97400836/217919037-70f9c329-754f-42fd-858a-8843945eb2bd.png">
<img width="692" alt="image" src="https://user-images.githubusercontent.com/97400836/217918980-295addb9-731f-402d-af39-5826fbd83f74.png">

With the same color:
<img width="691" alt="image" src="https://user-images.githubusercontent.com/97400836/217919247-a62443aa-d165-4d4e-9fd3-0694d009d26a.png">
<img width="682" alt="image" src="https://user-images.githubusercontent.com/97400836/217919935-61a371cb-57fa-4185-bd43-4a87e63f4df7.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 1.4.4

**Comment by hliebscher** [comment]
Can you Send the Link to stl file?

**Comment by rovili** [comment]
Hi hliebscher, 3mf and stl file-type are not allowed to be attached in his repo. 

Here are the links to STL and 3mf:
https://github.com/rovili/BambuLab/blob/main/leaf-coasters-pot-sculpted.3mf
https://github.com/rovili/BambuLab/blob/main/leaf-coasters-pot-sculpted.stl

**Comment by rovili** [comment]
@hliebscher any updates on this?
I noticed that it is also glitchy on not multicolor prints, some overhang (50°+) just don't get any "slowdowns" - but they do in Bambu Studio.

**Comment by hliebscher** [comment]
@rovili you can add 3mf as zip ;-)

**Comment by hliebscher** [comment]
it works for both

**Comment by rovili** [comment]
...I can reproduce it with more than one object. While it is totally fine with Bambu Studio. 
So something must be glitchy. Also color independent.
