### ISSUE TITLE
** BUILD FAILED **  macos

### ISSUE THREAD

**Issue by hliebscher** [SoftFever/BambuStudio-SoftFever#304]
The following build commands failed:
        CompileC /Users/hliebscher/github/BambuStudio-SoftFever-1/build/build/libslic3r_gui.build/Release/Objects-normal/arm64/Plater.o /Users/hliebscher/github/BambuStudio-SoftFever-1/src/slic3r/GUI/Plater.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'libslic3r_gui' from project 'BambuStudio')

after the last 2 patches the compiler has errors 

MAC M1 13.1

**Comment by hliebscher** [comment]
@SoftFever  slic3r/GUI/Plater.cpp:8132:17: error: no viable overloaded '='
        *max_lh = { layer_height };

this is the error

**Comment by SoftFever** [comment]
Okay, let me boot up my Mac machine:)Sent from my iPhoneOn 14 Feb 2023, at 2:58 PM, Heiko Liebscher ***@***.***> wrote:﻿
@SoftFever  slic3r/GUI/Plater.cpp:8132:17: error: no viable overloaded '='
*max_lh = { layer_height };
this is the error

**Comment by hliebscher** [comment]
i have fix this in #314 PR
