### ISSUE TITLE
macOS app is corrupted

### ISSUE THREAD

**Issue by Kowy54** [SoftFever/BambuStudio-SoftFever#305]
Trying to run on macOS 13.2. While opening I get error message that app is corrupted.

**Comment by hliebscher** [comment]
Have you read the note on the Main page about this issue and the articel that are linked? https://www.howtogeek.com/803598/app-is-damaged-and-cant-be-opened/

same at #274

**Comment by Kowy54** [comment]
No. It's firs time that I have this problem. This guide is working. Thanks.
