### ISSUE TITLE
Can´t open any BambuStudio for Mac

### ISSUE THREAD

**Issue by SA7BNT** [SoftFever/BambuStudio-SoftFever#315]
Hey,
just tested different releases for Mac_x86_64. But i can´t get none of them to open. 
I´m always getting 
<img width="258" alt="Screenshot 2023-02-15 at 11 09 28" src="https://user-images.githubusercontent.com/35367117/218997987-cb64e273-d367-4de0-9551-e88d1df4046d.png">

I´m running 
<img width="273" alt="Screenshot 2023-02-15 at 11 10 38" src="https://user-images.githubusercontent.com/35367117/218998205-4599f39e-3475-484e-a685-b99d6d1ee014.png">

Did i miss something to install??

**Comment by EuanWebster** [comment]
Same issue for me Macbook Pro 16" 2020, macOS Ventura x86.

**Comment by Munza2020** [comment]
Same as first post. Macbook Pro 15" 2017 Ventura 13.1

**Comment by EuanWebster** [comment]
> Hey, just tested different releases for Mac_x86_64. But i can´t get none of them to open. I´m always getting <img alt="Screenshot 2023-02-15 at 11 09 28" width="258" src="https://user-images.githubusercontent.com/35367117/218997987-cb64e273-d367-4de0-9551-e88d1df4046d.png">
> 
> I´m running <img alt="Screenshot 2023-02-15 at 11 10 38" width="273" src="https://user-images.githubusercontent.com/35367117/218998205-4599f39e-3475-484e-a685-b99d6d1ee014.png">
> 
> Did i miss something to install??

Are you able to raise this to a bug?

**Comment by hliebscher** [comment]
Have you read the note on the Main page about this issue and the articel that are linked? https://www.howtogeek.com/803598/app-is-damaged-and-cant-be-opened/

same at https://github.com/SoftFever/BambuStudio-SoftFever/issues/274

**Comment by EuanWebster** [comment]
> Have you read the note on the Main page about this issue and the articel that are linked? https://www.howtogeek.com/803598/app-is-damaged-and-cant-be-opened/
> 
> same at #274

Thank you, that worked perfectly!!

**Comment by SA7BNT** [comment]
> Have you read the note on the Main page about this issue and the articel that are linked? https://www.howtogeek.com/803598/app-is-damaged-and-cant-be-opened/
> 
> same at #274

Well i didn't get it so much attention to that post because i just read M1. Mine is not a M1. So maybe change the note to all Mac user´s 
Thanks for the hint. Was working for me to.

**Comment by Munza2020** [comment]
Thanks, that worked, but yes, I ignored note because it said for Apple M1 users as well. It is just for Apple users, the chip type is irrelevant.
