### ISSUE TITLE
[FEATURE] Use the "filename format" when exporting the 3MF

### ISSUE THREAD

**Issue by H4kunaM4tata** [SoftFever/BambuStudio-SoftFever#32]
Under normal circumstances, when exporting the g-code, you can have this beautiful file name

![image](https://user-images.githubusercontent.com/35049512/208324193-81a06225-890f-4033-9de9-00fd10bbd21a.png)

Within a folder with dozens of files, that allows you to easily identify the models, layer height, which filament, how many grams of filament and how many hours that model will take.

![image](https://user-images.githubusercontent.com/35049512/208324206-1a083d19-3172-4079-ba96-21a93ca7cbd1.png)

But when exporting the same project as 3MF, since you haven't saved anything, the project has no name so it generates this useless file name

![image](https://user-images.githubusercontent.com/35049512/208324230-85edacc7-7879-4160-8646-9a0f9f5390f1.png)

And as consequence, you have all these useless files that you cannot tell if you sliced with PLA, PLA+, PETG, ASA, you have no idea how long and if you have enough filament

![image](https://user-images.githubusercontent.com/35049512/208324455-3b27fd6c-8701-4491-a787-8cf6d4e4980f.png)

It would be a dream to be able to save the slicing as:

![image](https://user-images.githubusercontent.com/35049512/208324511-b007ee95-7d32-4746-8822-282980dac0bb.png)

Thank you

**Comment by zeroemso** [comment]
+1 buddy i was on the way to open a request too. thx.

**Comment by H4kunaM4tata** [comment]
> +1 buddy i was on the way to open a request too. thx.

I was supposed to open this request like ages ago but I kept forgetting.
It is becoming impossible to identify the right files now, too much printing haha

**Comment by zeroemso** [comment]
if you came from klipper it is very hard without a mainsail "file section" now i have to name my files different from vorons + no Folders on SDCard is a real pita.

**Comment by SoftFever** [comment]
Done. 
New changes will be included in the next update

**Comment by SoftFever** [comment]
![image](https://user-images.githubusercontent.com/103989404/209423062-5cec2951-1295-4e45-8cf5-170eb4d44117.png)

**Comment by H4kunaM4tata** [comment]
> ![image](https://user-images.githubusercontent.com/103989404/209423062-5cec2951-1295-4e45-8cf5-170eb4d44117.png)
> 

Yes 🙌
Are you able to add 2 more info??

The layer height and the grams of filament used like the screenshot I shared???
Then you have all the important information on the filename.

Thank you so much for looking into this.

**Comment by SoftFever** [comment]
> > ![image](https://user-images.githubusercontent.com/103989404/209423062-5cec2951-1295-4e45-8cf5-170eb4d44117.png)
> 
> Yes 🙌 Are you able to add 2 more info??
> 
> The layer height and the grams of filament used like the screenshot I shared??? Then you have all the important information on the filename.
> 
> Thank you so much for looking into this.

The name is configurable just like the gcode file. You can customise it the way you liked

**Comment by SoftFever** [comment]
> PrusaSlicer here.
> 
> I like to don't depend on extra stuff as less as possible so this format:
> 
> `{input_filename_base}_{layer_height}mm_{filament_type[0]}_{print_time}_{round(total_weight)}g.gcode`
> 
> Gives me a gorgeous filename: `Mandalorian_toothbrush_holder_0.2mm_PLA_1h56m_16g.gcode `
> 
> It is easy to find stuff, I don't need to load the file anywhere to see anything, its filename tells me everything I need to know. On your cause I would have:
> 
> * `X1C_Mandalorian_toothbrush_holder_0.2mm_PLA_1h56m_16g.gcode `
> * `Voron_Mandalorian_toothbrush_holder_0.2mm_PLA_1h56m_16g.gcode `
> 
> I am hoping this is something "easy" to implement. My OCD is going wild hahaha

Have you tried this file name format for the gcode file name? It should also work in bs sf version

**Comment by H4kunaM4tata** [comment]
@SoftFever yes, I've tried, copy/paste from PrusaSlicer and it works just fine ONLY if you are exporting as g-code.

I believe is File > Export > Export to g-code

But it doesn't work exporting as 3MF, top right corner. 
That becomes a pain if you export a lot of models having to do all that work and the printer won't load thumbnail so it isn't practical.

If exporting as 3MF it also reads the g-code field you introduced on SoftFever, that would be perfect.

Thank you and Marry Christmas.

**Comment by SoftFever** [comment]
> @SoftFever yes, I've tried, copy/paste from PrusaSlicer and it works just fine ONLY if you are exporting as g-code.
> 
> I believe is File > Export > Export to g-code
> 
> But it doesn't work exporting as 3MF, top right corner. That becomes a pain if you export a lot of models having to do all that work and the printer won't load thumbnail so it isn't practical.
> 
> If exporting as 3MF it also reads the g-code field you introduced on SoftFever, that would be perfect.
> 
> Thank you and Marry Christmas.



> If exporting as 3MF it also reads the g-code field you introduced on SoftFever, that would be perfect.
> 

Yes, this is the case.

Thanks, merry Christmas and happy New Year!
