### ISSUE TITLE
Unable to run under macOS 12.6

### ISSUE THREAD

**Issue by macminoz** [SoftFever/BambuStudio-SoftFever#321]
hi there, I downloaded twice but I got the same error:
![Screenshot 2023-02-16 at 23 27 21](https://user-images.githubusercontent.com/60092898/219501267-aaa87862-36c5-4e67-9432-825c48972796.png)

even with terminal no luck

`macmino@ MacOS % strings ./BambuStudio
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun`

**Comment by hliebscher** [comment]
Have you read the note on the Main page about this issue and the articel that are linked? https://www.howtogeek.com/803598/app-is-damaged-and-cant-be-opened/

same at https://github.com/SoftFever/BambuStudio-SoftFever/issues/274

**Comment by macminoz** [comment]
this solved my issue! thanks
