### ISSUE TITLE
unable to print directly from slicer with pull request #319

### ISSUE THREAD

**Issue by davidja92** [SoftFever/BambuStudio-SoftFever#322]
**Describe the bug**
when using pull request #319 nightly, the print slices fine but when pressing the print plate or print all button nothing happens. I can send the file to the printer wirelessly then print from the screen. i understand its a nightly just wanted to point it out thanks. I have determined this only occurs on the newly added calibration tests. normal sliced objects work fine

**3mf File for This Bug**
newly added calibration tests, ringing,vfa and temp tower

**To Reproduce**
use nightly pull request #319 and try to print directly from the slicer.

**Expected behavior**
pressing print plate or print all sends the .3mf to the printer and auto starts the print

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 11 
 - Version 1.4.4 nightly #319

**Comment by hliebscher** [comment]
do you have merge the #319? but the newly added calibration tests, ringing,vfa and temp tower are in [7fe5b84](https://github.com/SoftFever/BambuStudio-SoftFever/commit/7fe5b84c41746a9fd2a73c09644f83f975283453)
[last week](https://github.com/SoftFever/BambuStudio-SoftFever/commit/7fe5b84c41746a9fd2a73c09644f83f975283453)
not in 319
witch printer do you use?

**Comment by SoftFever** [comment]
Thanks for the feedback.
Fixed.

**Comment by SoftFever** [comment]
Closing as it is fixed.
Feel free to reopen it in case you still have issues
