### ISSUE TITLE
Voron origin center of bed

### ISSUE THREAD

**Issue by BlackStump** [SoftFever/BambuStudio-SoftFever#331]
I have tried on a couple occasions to use this slicer but not being able to set the Origin to the bed center is holding me up.
I have setup the Voron 300x300 to have the Origin in the center of the bed same as the Delta printer I have.
![bambooa](https://user-images.githubusercontent.com/26130487/220039575-d405d92a-e016-49f0-a8f9-50cd35f56e3f.png)
looks like it is just about there - X origin is greyed out while Y origin I can change to 150

hopefully a simple fix

thanks

**Comment by rovili** [comment]
You might set up something wrong.

The origin (0.0) of a Voron, in any size, must be at the left lower corner. You cannot set it up the same way as a Delta, because the Delta must have the origin in the middle of the bed.

**Comment by BlackStump** [comment]
This is the only slicer known to me that you can't set the Origin to the bed center.
Slicers that can be set to bed center 
PrusaSlicer
SuperSlicer
Ideamaker
Icesl
Kisslicer
Simplify3D

**Comment by BlackStump** [comment]
examples
![Superslicer](https://user-images.githubusercontent.com/26130487/220188836-708efbeb-69c7-43c7-bc7b-271af5a6a693.png)
![ideamaker](https://user-images.githubusercontent.com/26130487/220188853-d29e7d7e-f449-42de-a184-55e09cbcdc24.png)
![cura](https://user-images.githubusercontent.com/26130487/220189338-137dc3bf-877a-415e-af20-41b180c8020e.png)

**Comment by SoftFever** [comment]
It needs some work to support changing the origin(not the UI). I intentionally cripple the UI so UI won't accidentally change it.

**Comment by BlackStump** [comment]
fair enough
