### ISSUE TITLE
Gap infill is too aggressive

### ISSUE THREAD

**Issue by rovili** [SoftFever/BambuStudio-SoftFever#334]
The Gap infill is very aggressive and fills spots where actually nothing is to fill and it produces "zits".

It would be great if you could give us, such as SuperSlicer does, the possibility to adjust the Gap Infill threshold.

Please see an example with SoftFever:
<img width="1274" alt="image" src="https://user-images.githubusercontent.com/97400836/220183036-c6d97971-ad99-4b8f-a084-df9ed5798fc1.png">

With SuperSlicer:
<img width="872" alt="image" src="https://user-images.githubusercontent.com/97400836/220183495-f4645dd1-cdc0-441c-92d6-28bd6c000c7d.png">

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/97400836/220183810-6ebfeaa2-eac8-4a6e-b9d5-aae3e7840110.png">

**Comment by hliebscher** [comment]
can you zip the 3mf an attach for testing?

**Comment by SoftFever** [comment]
We have gap fill filter feature.
![image](https://user-images.githubusercontent.com/103989404/220215925-9af764a6-5641-4238-aae7-a940070281d0.png)
However, this option won't affect top/bottom layers at the moment.
1.4.5 will allow filtering out of all gap fills.

**Comment by rovili** [comment]
That is great news! Thanks a lot for your effort in this project! =)

**Comment by SoftFever** [comment]
Looks like we have sorted out the problem.
Closing it.
