### ISSUE TITLE
OpenGL support

### ISSUE THREAD

**Issue by chanders** [SoftFever/BambuStudio-SoftFever#34]
Is it possible to add compatibility for video cards that doesn't have OpenGL 2.0 like SuperSlicer does via command line parameters?

**Comment by SoftFever** [comment]
Are you referring `--sw-renderer` parameter?

**Comment by ercoleg** [comment]
hello,
I'm interested to know if there is any option similar to superslicer --sw-renderer parameter to use OrcaSlicer on an old pc.
thank you for your support
