### ISSUE TITLE
Single wall top surface with Arachne

### ISSUE THREAD

**Issue by Ibot-11** [SoftFever/BambuStudio-SoftFever#340]
It would be really nice if single wall top surface would be available with the Arachne wall generator. 
This is the only reason why I'm still using the classic wall generator.
I don’t know how hard this is to implement, but I would really love seeing it added.

**Comment by liftbag** [comment]
I forwarded the same request to Bambu Studio, and they seem to have accepted it. It shouldn't be complicated.

https://github.com/bambulab/BambuStudio/issues/1315

**Comment by SoftFever** [comment]
Implemented in dev build.
Will be available in new relase
