### ISSUE TITLE
Last Mac Release is corrupt

### ISSUE THREAD

**Issue by christianjou** [SoftFever/BambuStudio-SoftFever#35]
**Describe the bug**

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows]

**Comment by christianjou** [comment]
when i try to install the program, i get the message that the file is damaged.

Version: Mac/Intel

**Comment by SoftFever** [comment]
> when i try to install the program, i get the message that the file is damaged.
> 
> Version: Mac/Intel OS MONTEREY

Please check this; https://github.com/SoftFever/BambuStudio-SoftFever#1-for-apple-m1-users-please-take-a-look-at-this-article-about-how-to-run-unsigned-applications-on-your-machine-or-better-you-can-build-it-from-the-source-codes-if-you-want

**Comment by christianjou** [comment]
I do not have a M1 but an Intel.

**Comment by hliebscher** [comment]
Both versions  for MAC 1.4 for M1 and intel are working

https://support.apple.com/de-de/guide/mac-help/mh40616/mac
