### ISSUE TITLE
Failed to Getting Network Plugin

### ISSUE THREAD

**Issue by christianjou** [SoftFever/BambuStudio-SoftFever#36]
Once it is launch, no way to connect to have the network plugin
So i can not connect to my account.

<img width="575" alt="Capture d’écran 2022-12-20 à 13 15 59" src="https://user-images.githubusercontent.com/72012052/208665607-7245913d-25b5-4d61-b791-9115de939721.png">

Mac OS INTEL/MONTEREY

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows]

**Comment by hliebscher** [comment]
we have a discussion link

https://github.com/SoftFever/BambuStudio-SoftFever/discussions/33

pls wait some hours and than it works...
you can use the Studio without network pluging for non Bambu printer
sending of your GCode to non Babmu printer works

**Comment by SoftFever** [comment]
Close as duplicated with #33 .
