### ISSUE TITLE
variables first_layer_print_min[0] with wrong values on second print plate

### ISSUE THREAD

**Issue by hliebscher** [SoftFever/BambuStudio-SoftFever#37]
I use M557 for define Mesh Area

M557 X{first_layer_print_min[0]}:{first_layer_print_max[0]} Y{first_layer_print_min[1]}:{first_layer_print_max[1]} S25

if i use a second build plate  i get wrong values in GCODE back

**M557 X804.147:854.147 Y-531.917:-481.917 S25**

the part size is 50x50 mm 

with the BambuStudio org it is the same

**Comment by SoftFever** [comment]
It works fine for me.
Can you try the test project attached?
![image](https://user-images.githubusercontent.com/103989404/208690548-ba1eae5f-5cbb-4f29-9cb7-7d7d90e0feab.png)
[mesh_area_test.zip](https://github.com/SoftFever/BambuStudio-SoftFever/files/10269295/mesh_area_test.zip)

**Comment by hliebscher** [comment]
I found the Bug !!!!
 it works only with **one plate**
it you place some parts to second place the slicer take x0 y0 from the first plate!

**Comment by hliebscher** [comment]
one moment

**Comment by hliebscher** [comment]
yes the same bug for alternative printers 
bambu have no button to export gcode

**Comment by hliebscher** [comment]
it is the same bug

;===== bed leveling ==================================
M1002 judge_flag g29_before_print_flag
M622 J1

    M1002 gcode_claim_action : 1
    G29 A X353.451 Y85.9557 I50 J50
    M400
    M500 ; save cali data

M623
;===== bed leveling end ================================

**Comment by hliebscher** [comment]
BAMBULAB

We have fixed it in internal version and will be included in next release.
Thank you very much for reporting issue to keep software improved!

**Comment by SoftFever** [comment]
fixed

**Comment by hliebscher** [comment]
@SoftFever THANKS !!!!!!!!
