### ISSUE TITLE
Slicer setup wizard blank

### ISSUE THREAD

**Issue by DVSVIDEO** [SoftFever/BambuStudio-SoftFever#370]
**Describe the bug**
The slicer not starting

**3mf File for This Bug**
Not start, not 3mf
**To Reproduce**
1. Go to 'BambuStudio-SoftFever_V1.4.5_Win64'
2. Click on 'Bambu-studio.exe'
3. start software, appear the setup wizard screen, and nothing to see
4. This blank screen not allow next step (not start)
5. The window is movable, application not freezing
6. Quiting the program only with taskmanager

**Expected behavior**
some choice config an else

**Screenshots**
![BSSF](https://user-images.githubusercontent.com/96373457/221348622-24a13eed-f04d-40a0-ae29-6e74b19edafb.jpg)

**Desktop (please complete the following information):**
 - OS: Win10 enterprise 64bit

**Comment by SoftFever** [comment]
Can you install these two runtimes:
https://github.com/SoftFever/BambuStudio-SoftFever#2-if-you-have-troubles-to-run-the-build-you-might-need-to-install-following-runtimes

**Comment by DVSVIDEO** [comment]
Ohhh .... thanks!
the edge runtime solve the problem:
![BSSF_ok](https://user-images.githubusercontent.com/96373457/221429522-3e7114a5-5a91-44b1-9553-10741eea401b.jpg)
