### ISSUE TITLE
Crash unexpectedly when adding text into model

### ISSUE THREAD

**Issue by Alvinpan86** [SoftFever/BambuStudio-SoftFever#40]
**Crash unexpectedly when adding text into model**
Running on Mac (Intel) OS Ventura.

**To Reproduce**
1. When trying to add text to model, bambu studio crashes unexpectedly.

**Desktop (please complete the following information):**
 - OS: Mac
 - Ventura
[Error Report.txt](https://github.com/SoftFever/BambuStudio-SoftFever/files/10278570/Error.Report.txt)

**Comment by SoftFever** [comment]
It's specific to Mac Intel machines. I have no spare bandwidth to investigate it.
We need volunteers to look into this issue.

-SoftFever

**Comment by GiaPag** [comment]
I have this bug only in old version 1.3.4, i have no problems on latest release
