### ISSUE TITLE
Missing layers when slicing with latest BambuStudio

### ISSUE THREAD

**Issue by Guilouz** [SoftFever/BambuStudio-SoftFever#420]
**Describe the bug**

Missing layers when slicing.

**File for This Bug**

Tested with many files in different format (stl, 3mf, step), same issue.

[35x35_0.4mm_nozzle_flowrate_calibration.stl.zip](https://github.com/SoftFever/BambuStudio-SoftFever/files/10886637/35x35_0.4mm_nozzle_flowrate_calibration.stl.zip)

**To Reproduce**

Just install latest BambuStudio on macOS

**Screenshots**

![331725877_2127042837494308_7736453878498481701_n](https://user-images.githubusercontent.com/12702322/222839984-163d9508-2144-48b7-82b4-b5496670120d.jpg)

![332099566_1702435923519659_1287998195430035929_n](https://user-images.githubusercontent.com/12702322/222840008-4d2a1882-3fd9-4ebe-913c-1bb7f8e9ccba.jpg)

No issue with SofFever fork :

![331745992_236262445410258_5665490162902307276_n](https://user-images.githubusercontent.com/12702322/222840160-60a10e9d-d9a0-4f4d-910c-a16c4716240d.jpg)

**Printer model**

Bambulab X1 Carbon

**Desktop**

 - OS: MacOS Ventura

**Comment by SoftFever** [comment]
Hi @Guilouz ,

Did you mean it's a bug in BambuStudio only?
If that's the case, I'd suggest you post this on BambuStudio's repo.

**Comment by Guilouz** [comment]
Ahh yes sorry! I have posted this in wrong repo. Sorry.
