### ISSUE TITLE
Bambu Studio Info. Too large layer height. Reset to 0.500

### ISSUE THREAD

**Issue by olivogt** [SoftFever/BambuStudio-SoftFever#428]
Hi - is the above intentional? At the moment it seems I cannot set layer heights larger than 0.5mm.
This would mean no support for 0.8mm nozzles and above - right?

Thanks,
Oliver

**Comment by SoftFever** [comment]
this value limits layer height, you need to change it 
![image](https://user-images.githubusercontent.com/103989404/222968385-46f47db1-75b6-467b-878c-f8ec0a937dc8.png)

**Comment by olivogt** [comment]
I was just about to say I found it too ... ;-)

Thanks,
Oliver

**Comment by domik82** [comment]
I honestly think it should be mentioned somewhere in the popup box that it can be changed and how to find it. 

I'm trying to print this Fast-Printing Modular Drawer System (Vase Mode) - https://www.printables.com/model/139570-fast-printing-modular-drawer-system-vase-mode

And it suggests that:

> I use a 0.8mm line width for higher strength (a 0.6mm line width should also give good results, but will be less strong), 0.32 layer height, and 25-30mm/s wall speed. 
> 
> I use a 0.4mm nozzle for all parts. 
> 
> No supports required for any parts.

It was quite difficult to figure out where I should change something to try to print with the same settings.
