### ISSUE TITLE
Flow ratio cannot be set as percentage

### ISSUE THREAD

**Issue by suchabadperson** [SoftFever/BambuStudio-SoftFever#429]
In the of the flow rate guide on the wiki, the flow ratio is set as a percentage, but in the latest version the field is a fixed value and cannot be set as a percentage, so the flow rate test would not work (you would need to set the values manually).

![SCR-20230305-kj5](https://user-images.githubusercontent.com/65729856/222964321-3b637c4a-90b9-4217-8843-da66e5f51009.png)

**Comment by SoftFever** [comment]
Flow ratio is a factor instead of a percentage value now.
1.1 means 110% here.

With factor, we can change the flow ratio much more granularly.
It is also consistent with the flow ratio setting in the filament setting.
