### ISSUE TITLE
[bug]  Layer time view is "nerfed" by first layers

### ISSUE THREAD

**Issue by psiberfunk** [SoftFever/BambuStudio-SoftFever#43]
The new layer time feature is great.. but it has a fatal flaw:  The first layer is almost always much slower than other layers.  Particularly with the X1, the first layer can include the purge / PA lines.  The attached example X1 3mf project shows what this looks like, and how, even with logarithmic view, the layer time view is useless, because it's all one color.

I would suggest that layer time specifically exclude the first layer in the color scale Min/Max determination, and that the first layer simply be colored grey or the minimum color (if appropriate).

![image](https://user-images.githubusercontent.com/19777571/209047530-a0528196-6f10-4ea0-b523-2ca28c1d30c0.png)

**Test file to show this:**
[Test.zip](https://github.com/SoftFever/BambuStudio-SoftFever/files/10283418/Test.zip)

**Comment by SoftFever** [comment]
It's a known issue for BBL printers.
Has been fixed in 41078e6555a2397f1150aa8edb1d028b52f993a
