### ISSUE TITLE
Shrinkage Compensation

### ISSUE THREAD

**Issue by DanielGroot** [SoftFever/BambuStudio-SoftFever#432]
**Is your feature request related to a problem? Please describe.**
My filaments are kinda wonky so i need some shrinkage compensation for some filaments. In superslicer there's an option for that, but I'm missing it in BambuStudio. Therer is a x-y countour compensation but that doesnt just scale up the model by a given procent

**Describe the solution you'd like**
I'd like a feature where you type in a percentage that you calculate by printing a small cube and see how much smaller it's than you requested. And the slicer will compensate for that by scaling up that model by that x procent

**Comment by SoftFever** [comment]
Hi,

We already have a ticket for this FR #360 
This feature has been implemented in the dev branch, and will be available in the next release.
If you want to try now, download the latest nightly build here: https://github.com/SoftFever/BambuStudio-SoftFever/actions/workflows/build_win.yml.

**Comment by SoftFever** [comment]
Feel free to comment on that ticket.
I'm closing this one as it's duplicated.
