### ISSUE TITLE
First layer check on unprinted area

### ISSUE THREAD

**Issue by SwagDad99** [SoftFever/BambuStudio-SoftFever#49]
**Describe the bug**
When doing 'Print by Object' after the first layer of the first object is done, it does the first layer check on the areas for ALL of the object's first layers, even though only the first object is being printed.

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**
1. Slice plate with multiple objects on it and select 'By Object' in the Print Sequence drop box
2. Print the plate
3. After the first layer is printed of the first object, notice that it checks where the unprinted objects will be as well.

**Expected behavior**
Only check the first layer of the object printed.  I am not sure if it will check the first layer of subsequent models will be checked...

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows]

**Comment by SoftFever** [comment]
This issue is very X1 printer specific.
I don't have the spare bandwidth to fix this issue personally. 
Hopefully, BL can fix it soon.

Thanks s for creating the issue anyway.

-SoftFever
