### ISSUE TITLE
Compare Profiles

### ISSUE THREAD

**Issue by Ibot-11** [SoftFever/BambuStudio-SoftFever#51]
**Is your feature request related to a problem? Please describe.**
Comparing profiles is pretty annoying atm.

**Describe the solution you'd like**
A comparing tool like prusaslicer or superslicer have.
That would be really nice.

![image](https://user-images.githubusercontent.com/84148069/209444701-b82a13d1-a480-43c3-b657-a3f15677c3bd.png)

**Comment by hliebscher** [comment]
it is working
![compare](https://user-images.githubusercontent.com/9274162/209466822-8161f84f-8181-4385-ae1b-2e90177ed3e1.jpg)

**Comment by Ibot-11** [comment]
So is this already in the slicer or will this be added soon?
Maybe i couldn't find this anywhere.

**Comment by SoftFever** [comment]
It's already there.
This feature comes from the upstream.
![image](https://user-images.githubusercontent.com/103989404/209479171-b8649336-b846-4aa3-9294-98e6a0445bb3.png)

**Comment by Ibot-11** [comment]
ok, I found the issue. The language was set to german. And somehow the button disappears then. When I change to English, it's there.
![image](https://user-images.githubusercontent.com/84148069/209480290-23986c00-063e-4064-935f-072fed247567.png)
