### ISSUE TITLE
Add Shrinkage to Filament

### ISSUE THREAD

**Issue by vonwange** [SoftFever/BambuStudio-SoftFever#52]
**Is your feature request related to a problem? Please describe.**
Define Skrinkage in % to Filament. 

**Describe the solution you'd like**
A simple % multiplier (i.e. 103% -> 1,03 bigger STL dimensions)

**Describe alternatives you've considered**
Manuel resizing

**Additional context**
By defining a skrinkage multiplier it is very easy to achieve correct STL dimensions independent of used filament. Also no re-sizing of objects is required. 

SuperSlicer has implemented this very well. Maybe worth copy 'n' pasting ...

Thanks for considering.

**Comment by Tolzad** [comment]
@SoftFever 

Has this suggestion been added to the current version? Or will I need to wait for the next update?
Unable to find the option in the filament settings. I have seen the X-Y compensation under precision though I don't believe this is the same as the process superslicer uses that vonwage mentioned.

Thank you for the hard work!
