### ISSUE TITLE
Extrusion multiplier per object

### ISSUE THREAD

**Issue by Ibot-11** [SoftFever/BambuStudio-SoftFever#56]
**Is your feature request related to a problem? Please describe.**
Tuning the extrusion multiplier is pretty laborious. You have to start a new print for every value you want to try.

**Describe the solution you'd like**
Adding the extrusion multiplier as a value you can set in the object processes.
The same way you would do that in prusaslicer and superslicer.

**Comment by SoftFever** [comment]
This has been implemented 7e1a2840e569770380e55fac2d4cf781054ecfca
Perfect timing ;)
