### ISSUE TITLE
Unable to load Bambulab network plugin.  Softfever 1.4.0 on MacOS 12.6.1

### ISSUE THREAD

**Issue by Tonyknz** [SoftFever/BambuStudio-SoftFever#62]
**Describe the bug**
Bambuslicer application installs and then advises Network plugin not found.

Click to install network plug-in starts the process and then fails with error message "Failed to download the plug-in. Please check your firewall settings and vpn software, check and retry.

As a test on the same machine, an installation of Bambuslicer v1.4.1.52 installed the network plug-in without any problem.

**Comment by mrmccain9** [comment]
> **Describe the bug** Bambuslicer application installs and then advises Network plugin not found.
> 
> Click to install network plug-in starts the process and then fails with error message "Failed to download the plug-in. Please check your firewall settings and vpn software, check and retry.
> 
> As a test on the same machine, an installation of Bambuslicer v1.4.1.52 installed the network plug-in without any problem.

Same issue here on Softfever 1.4.0, but on MacOS 11.7

**Comment by SoftFever** [comment]
I have no clue why it fails on Mac Intel at the moment.
There is a discussion on it #33 
A workaround for it is to manually download it.

**Comment by Tonyknz** [comment]
Manual download of the plug-in following instructions in #33 works.
