### ISSUE TITLE
Support for RatRig Printers

### ISSUE THREAD

**Issue by erebus04** [SoftFever/BambuStudio-SoftFever#67]
I am currently creating profiles for the RatRig printers.
For the V-Core 3 and the V-Minion.
Is there interest here to integrate this into the standard?
@SoftFever 

I have attached some screenshots.

![Bed](https://user-images.githubusercontent.com/34960970/209700634-081211dc-4727-4e0d-8b69-a3d4a47708a0.png)
![Process](https://user-images.githubusercontent.com/34960970/209700638-3506f162-000c-46d6-97b8-32f379f0d374.png)
![Filament](https://user-images.githubusercontent.com/34960970/209700639-53ff0b8e-f636-4e9d-9342-76f631ede0ba.png)
![Printer-Settings](https://user-images.githubusercontent.com/34960970/209700640-b7d94be1-a8ec-4576-aebd-30ea3f49185f.png)
![Printer-Selection](https://user-images.githubusercontent.com/34960970/209700642-ea9986b4-e2fc-4b5d-8aa3-1d2ca0337f40.png)

**Comment by hliebscher** [comment]
I can Test an integrate via PR 
I have VCore 3.1 with Klipper und RRF

**Comment by erebus04** [comment]
Greate, when I have everything created, I make a PR

**Comment by SoftFever** [comment]
> I am currently creating profiles for the RatRig printers. For the V-Core 3 and the V-Minion. Is there interest here to integrate this into the standard? @SoftFever
> 
> I have attached some screenshots.
> 
> ![Bed](https://user-images.githubusercontent.com/34960970/209700634-081211dc-4727-4e0d-8b69-a3d4a47708a0.png) ![Process](https://user-images.githubusercontent.com/34960970/209700638-3506f162-000c-46d6-97b8-32f379f0d374.png) ![Filament](https://user-images.githubusercontent.com/34960970/209700639-53ff0b8e-f636-4e9d-9342-76f631ede0ba.png) ![Printer-Settings](https://user-images.githubusercontent.com/34960970/209700640-b7d94be1-a8ec-4576-aebd-30ea3f49185f.png) ![Printer-Selection](https://user-images.githubusercontent.com/34960970/209700642-ea9986b4-e2fc-4b5d-8aa3-1d2ca0337f40.png)

Absolutely welcomed :)

**Comment by erebus04** [comment]
Pull Request are created

**Comment by SoftFever** [comment]
Merged.
Thanks, @erebus04
