### ISSUE TITLE
Add support for Ankermake M5

### ISSUE THREAD

**Issue by AutismeLuxembourg** [SoftFever/BambuStudio-SoftFever#68]

**Comment by SoftFever** [comment]
Added in 69a21f09

**Comment by SoftFever** [comment]
![image](https://user-images.githubusercontent.com/103989404/210059448-cdc31085-353f-49b7-b82a-b9de207f2438.png)
![image](https://user-images.githubusercontent.com/103989404/210059583-b61c6a2d-f18d-4bc2-8e54-d0172c8e6723.png)
