### ISSUE TITLE
[Feature Request] Visualize Layer times in preview

### ISSUE THREAD

**Issue by psiberfunk** [SoftFever/BambuStudio-SoftFever#7]
It would be useful, if possible, to have a color-coded "layer time" view to help highlight where layer time/cooling settings may be causing print quality issues.

This would be similar to visualizing Fan speed, but looking at things from a layer-time perspective, which is particularly useful on filament types (like ABS/nylon) that really don't like fan cooling.  In these instances, longer minimum layer times may be preferable to speeding up or turning on the fan.

**Comment by kvnper** [comment]
I second this idea

**Comment by SoftFever** [comment]
I like this feature too!
Working on it.
It should be available in the next release.
