### ISSUE TITLE
Add additional Parameters for Seam

### ISSUE THREAD

**Issue by erebus04** [SoftFever/BambuStudio-SoftFever#72]
In SuperSlicer there are two additional Parameters for Seam.
With this Parameters, the Seam can be reduced to a minimum.
The print quality can be increased.

![Seam](https://user-images.githubusercontent.com/34960970/209834530-b0516437-0879-4236-8378-58a07297d956.png)
![Angle_Cost](https://user-images.githubusercontent.com/34960970/209834535-98c119b4-770c-4c00-955b-c4e2b2c08d8d.png)
![Travel_Cost](https://user-images.githubusercontent.com/34960970/209834539-7b6fce2b-515e-4ce7-82f7-03b8ec6f482f.png)

**Comment by Ibot-11** [comment]
Bambustudio already uses the new prusaslicer seam placement algorithm. This already works way better than the superslicer seam placement which is still based on the old algorithm. Therefore I don’t see a reason why this would be useful.
