### ISSUE TITLE
Application will not run

### ISSUE THREAD

**Issue by schmidtc89** [SoftFever/BambuStudio-SoftFever#73]
**Describe the bug**
When I try to run the exe the application will not start. I have installed the listed dependencies but that makes no difference. I can however run the Bambu labs official app without a problem.

 - OS: Windows 10
 - Version 1.4

**Comment by SoftFever** [comment]
Can you provide the info of your CPU and GPU?

**Comment by schmidtc89** [comment]
CPU is a old AMD 1090T and GPU is GTX 1080.

**Comment by SoftFever** [comment]
Yeah, this CPU is too old, it doesn't support AVX instruction set.
I will remove AVX in the next update since I see little performance difference.

**Comment by schmidtc89** [comment]
Oh ok, thank you. I’ll give it a try then.
