### ISSUE TITLE
M1 Mac - Error when opening the program

### ISSUE THREAD

**Issue by DIYLAB-DE** [SoftFever/BambuStudio-SoftFever#78]
**Describe the bug**
When opening the program on a M1 Mac, I get a message that the program is corrupted and cannot be run. See screenshot.

**Screenshot**
![error](https://user-images.githubusercontent.com/87319037/210058286-f8c5faa1-4dd7-4045-828d-8150ab927ccf.png)

**Desktop (please complete the following information):**
 - OS: macOS 13.0.1 Ventura on M1 Mac

**Comment by SoftFever** [comment]
Please check NOTE 1 part in the release notes: https://github.com/SoftFever/BambuStudio-SoftFever/releases/tag/v1.4.0

**Comment by DIYLAB-DE** [comment]
**Very nice, it works, thank you!**
Is there a possibility later to sign this program properly?

**Comment by SoftFever** [comment]
Sure.
I will do that when there are more Mac users.
