### ISSUE TITLE
build Mac M1 version make error

### ISSUE THREAD

**Issue by hliebscher** [SoftFever/BambuStudio-SoftFever#82]
Hi

after Change the         build_release_macos.sh   is it not possible to build the Mac Version

Apple M1
Ventura 13.1
xcode 14.2
cmake version 3.25.1

ERROR

make: *** No rule to make target `ALL_BUILD'.  Stop.
-- The C compiler identification is AppleClang 14.0.0.14000029
-- The CXX compiler identification is AppleClang 14.0.0.14000029

The same with intel i5 
-- Build files have been written to: /Users/hliebscher/github/BambuStudio-SoftFever/deps/build
make: *** No rule to make target `ALL_BUILD'.  Stop.
-- The C compiler identification is AppleClang 14.0.0.14000029
-- The CXX compiler identification is AppleClang 14.0.0.14000029

**Comment by SoftFever** [comment]
Can you try the latest version?

**Comment by hliebscher** [comment]
it works perfekt now THANKS!!!!
