### ISSUE TITLE
CALIBRATION for mac

### ISSUE THREAD

**Issue by christianjou** [SoftFever/BambuStudio-SoftFever#90]
Hi, will it be possible to add the "calibration menu" for MAC  ?

**Comment by SoftFever** [comment]
@christianjou It's there. Check the menu bar

**Comment by mrskoku** [comment]
i have this problem as well. mac arm 1.4.1 version. does this needs to be enabled somehow ?
<img width="980" alt="Zrzut ekranu 2023-01-3 o 15 11 48" src="https://user-images.githubusercontent.com/58340664/210374136-7ade3886-a8e9-4efc-9fe4-e6032b1d9825.png">
