### ISSUE TITLE
Bug: The PA line calibration uses outside wall speed without taking into consideration the max flow rate for the selected filament

### ISSUE THREAD

**Issue by jaanshgo** [SoftFever/BambuStudio-SoftFever#91]
I was trying to calibrate a silk filament and I saw that the flow was very high when the max is set to 10mm3/s. I solved it by lowering outside wall speed but I think this should be solved so people don't do the calibration at a higher than intended flow.

**Comment by psiberfunk** [comment]
@jaanshgo  and @SoftFever  I think my #94 is a duplicate to this, but I explain suggested fixes in a little more detail.  Maybe close this one ?

**Comment by SoftFever** [comment]
Thanks, @jaanshgo, and @psiberfunk .
I will fix it in the next version.

**Comment by SoftFever** [comment]
Meanwhile, I will close this one.
Let's track it in #94
