### ISSUE TITLE
Adjust PA calibration range

### ISSUE THREAD

**Issue by steven850** [SoftFever/BambuStudio-SoftFever#99]
We need to be able to adjust the range of the PA calibration values.  The included range does not work for TPU. We need a way to set a custom start and end value for the test.

**Comment by psiberfunk** [comment]
I agree .. a pop up with min/max/step size would be useful .. with defaults going to the existing numbers of course

**Comment by psiberfunk** [comment]
PS make sure validate that the pattern will fit on the bed in case the user sets unreasonable values like step size of 0.00001

**Comment by steven850** [comment]
Ideally also a way to adjust the min and max speed, so for some materials there limited to 30mm/s, so it going from 20 to 30 doesn't provide much of a difference in speed for a good comparison, so being able to drop the current 20mm/s to like 5, so having it go 5mm to 30mm/s would provide a better calibration for that material.

**Comment by psiberfunk** [comment]
You can already do that by setting the outer wall speed @steven850 .  Problem is , doesn’t respect volumetric flow rate limits , yet .. but that’s getting fixed in #94

**Comment by steven850** [comment]
@psiberfunk Yes but my point is, if I set that to 20mm/s, the test is just a line at a constant speed, there is then no speed change. need to be able to change the speed of the "slow part" of the test aswell. So the line will do for example 5 slow 20 fast.

**Comment by psiberfunk** [comment]
> @psiberfunk Yes but my point is, if I set that to 20mm/s, the test is just a line at a constant speed, there is then no speed change. need to be able to change the speed of the "slow part" of the test aswell. So the line will do for example 5 slow 20 fast.

I guess that’s true .. I’m trying to think of a case where 20 isn’t “slow” though … :)

**Comment by steven850** [comment]
When the max speed of the filament is 20 or 30, in that case need to drop down to 3 or 5mm/s  I have some TPU that wont do more then 2 cubic mm/s, so max print speed on that is like 20, hence needing these settings.

**Comment by psiberfunk** [comment]
> Ideally also a way to adjust the min and max speed, so for some materials there limited to 30mm/s, so it going from 20 to 30 doesn't provide much of a difference in speed for a good comparison, so being able to drop the current 20mm/s to like 5, so having it go 5mm to 30mm/s would provide a better calibration for that material.

Can I suggest maybe that you make this a separate ticket as it's arguably a separate feature/knob to turn ?

**Comment by bani6809** [comment]
starting value and step value would be useful. 0.098 seems to be the very bottom of Overture 95A TPU.
